# Generated by Django 2.1 on 2019-04-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionres', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uresponse', models.CharField(max_length=50)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionres.Questions')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Users')),
            ],
            options={
                'db_table': 'user_responses',
            },
        ),
    ]
